const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const core = require('../simulation-core.js');
const html = fs.readFileSync('index.html', 'utf8');
const inline = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]).join('\n');
const source = inline.slice(0, inline.indexOf('// The simulation runs off the main thread')) + '\nglobalThis.__test={simulate,DEFAULTS,buildRuinCurve};';
const context = { console, Math, Float64Array, Int32Array, Uint8Array, Date, Infinity, NavlogCore: core, document:{getElementById:()=>null}, globalThis:null };
context.globalThis=context; vm.createContext(context); vm.runInContext(source, context, {timeout:1000});
const {simulate, DEFAULTS, buildRuinCurve}=context.__test;
const common={...DEFAULTS, seed:444, proMode:true, startEq:10000000, startBtc:0, ret:0, vol:0, btcRet:0, btcVol:0, gasto:120000, swr:4, vida:0, hip:0, nur:0, brOn:false, burr:0, provOn:false, taxOn:true, useIrpfBrackets:true, taxRepatDelay:0, beckhamOn:true, beckhamYears:99};
const duringBeckham=simulate(common,4);
const untaxed=simulate({...common,taxOn:false},4);
assert.deepEqual(duringBeckham.series.map(x=>x.p50),untaxed.series.map(x=>x.p50),'Beckham period suspends progressive gains tax');
const fireMonthAll=new Int32Array(3000); fireMonthAll.fill(-1); fireMonthAll.set([12,12,12]);
const ruinMonth=new Int32Array(3000); ruinMonth.fill(-1); ruinMonth.set([14,14,14]);
const forcedOut=new Uint8Array(3000); forcedOut[1]=1; const licenseLossOut=new Uint8Array(3000); licenseLossOut[2]=1;
const curve=buildRuinCurve({fireMonthAll,ruinMonth,ruined:Uint8Array.from([1,1,1,...new Array(2997).fill(0)]),forcedOut,licenseLossOut},3000);
assert.equal(curve[0].atRisk,1,'ruin denominator includes voluntary FIRE only');
assert.equal(curve[0].pct,null,'small voluntary-only cohort is correctly marked insufficient rather than mixing forced exits');
assert.deepEqual(core.retirementCohortCounts({fireMonthAll,ruined:Uint8Array.from([1,1,1]),forcedOut,licenseLossOut},3),{voluntary:1,voluntaryRuined:1,forced:1,licenseLoss:1},'headline and charts use the same voluntary cohort while exposing forced exits and LOL separately');
const seedZeroA=core.seededRandom(0), seedZeroB=core.seededRandom(0), seedFallback=core.seededRandom(0x9e3779b9);
assert.equal(seedZeroA(),seedZeroB(),'seed zero remains reproducible');
assert.notEqual(seedZeroB(),seedFallback(),'seed zero does not collide with fallback seed');
assert.throws(()=>core.seededRandom(''),'blank seed is not silently made deterministic');
assert.equal(core.marginalSavingsTaxRate(1,300001),30,'large YTD gains use the top progressive savings bracket');
assert.equal(core.providentFirst(10,[{balance:100000,basis:0}],300001),true,'cheaper Provident bucket wins over savings gains at the top bracket');
assert.equal(core.providentFirst(19,[{balance:100000,basis:50000}],300001),false,'effective gains tax accounts for the savings basis fraction');
const safeScenario={id:'sc1',name:'Safe',color:'#1F7A4D',visible:true,series:[{year:2030,p10:1,p50:2,p90:3}],target:100,ageMed:'40',successRate:.8,params:{ageNow:28}};
const normalized=core.normalizeScenarios([safeScenario,{...safeScenario,id:'sc2',name:'<img src=x onerror=alert(1)>'},{...safeScenario,id:'sc3',color:'red'}],['ageNow'],['#1F7A4D']);
assert.equal(normalized.length,2,'scenario sanitizer rejects invalid color while retaining valid records');
assert.equal(normalized[1].name,'<img src=x onerror=alert(1)>','untrusted scenario labels are kept as data for safe text-node rendering');
assert.deepEqual(core.normalizeScenarios('{broken',['ageNow'],['#1F7A4D']),[],'corrupt scenario payload recovers to empty list');
assert.equal(core.historicalWithdrawalBacktest([0,0],100,120,1).length,2,'historical sequential withdrawal backtest evaluates every eligible start year');
assert.ok(core.historicalWithdrawalBacktest([0],100,120,1)[0].ruined,'historical backtest records depletion');
assert.equal(core.wealthTaxBase(100000,500000,true),600000,'owned property remains in wealth-tax base independent of FIRE-capital toggle');
assert.equal(core.beckhamApplies(true,20,20,6),true,'Beckham regime applies on the first resident month, including zero repatriation delay');
assert.equal(core.beckhamApplies(true,20,92,6),false,'Beckham regime ends after its configured month window');
assert.equal(core.sameParameterSnapshot({seed:null,ageNow:28},{ageNow:28,seed:null}),true,'snapshot equality is independent of key order');
assert.equal(core.sameParameterSnapshot({seed:0},{seed:1}),false,'current controls cannot reuse stale scenario results');
const wealthToggleFalse={...common, reOn:true, reValue:500000, reCountsFire:false, wealthTaxOn:true, wealthExempt:0, taxRepatDelay:0};
const propertyWealthResult=simulate(wealthToggleFalse,1);
assert.ok(propertyWealthResult.series.length,'property wealth-tax simulation completes when property is excluded as FIRE capital');
console.log('post-fix regressions: OK');
