const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const core = require('../simulation-core.js');
const html = fs.readFileSync('index.html', 'utf8');
const inline = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]).join('\n');
const source = inline.slice(0, inline.indexOf('// The simulation runs off the main thread')) + '\nglobalThis.__test={simulate,DEFAULTS,buildRuinCurve};';
const context = { console, Math, Float64Array, Int32Array, Uint8Array, Date, Infinity, NavlogCore: core, document:{getElementById:()=>null}, globalThis:null };
context.globalThis=context; vm.createContext(context); vm.runInContext(source, context, {timeout:1000});
const {simulate, DEFAULTS, buildRuinCurve}=context.__test;
const common={...DEFAULTS, seed:444, proMode:true, startEq:2000000, startBtc:0, ret:0, vol:0, btcRet:0, btcVol:0, gasto:120000, swr:4, vida:0, hip:0, nur:0, brOn:false, burr:0, provOn:false, taxOn:true, useIrpfBrackets:true, taxRepatDelay:0, beckhamOn:true, beckhamYears:99};
const duringBeckham=simulate(common,4);
const untaxed=simulate({...common,taxOn:false},4);
assert.deepEqual(duringBeckham.series.map(x=>x.p50),untaxed.series.map(x=>x.p50),'Beckham period suspends progressive gains tax');
const fireMonthAll=new Int32Array(3000); fireMonthAll.fill(-1); fireMonthAll.set([12,12,12]);
const ruinMonth=new Int32Array(3000); ruinMonth.fill(-1); ruinMonth.set([14,14,14]);
const forcedOut=new Uint8Array(3000); forcedOut[1]=1; const licenseLossOut=new Uint8Array(3000); licenseLossOut[2]=1;
const curve=buildRuinCurve({fireMonthAll,ruinMonth,ruined:Uint8Array.from([1,1,1,...new Array(2997).fill(0)]),forcedOut,licenseLossOut},3000);
assert.equal(curve[0].atRisk,1,'ruin denominator includes voluntary FIRE only');
assert.equal(curve[0].pct,null,'small voluntary-only cohort is correctly marked insufficient rather than mixing forced exits');
console.log('post-fix regressions: OK');